### ISSUE TITLE
Ver 1.2.0 not working in xcode 6.4

### ISSUE THREAD

**Issue by sudhiryadav** [icanzilb/JSONModel#445]
I tried to build ver 1.2.0 but it gives compilation errors in Xcode 6.4  

Errors:

/Users/.../JSONModel/JSONModelClassProperty.m
Error:(71, 60) expected '>'
Error:(71, 61) expected member name or ';' after declaration specifiers
Error:(71, 1) property requires fields to be named
Error:(71, 63) interface type cannot be statically allocated
Error:(71, 65) expected ';' at end of declaration list
Error:(71, 65) expected identifier or '('

/Users/../JSONModel/JSONModelClassProperty.m
Error:(33, 14) property 'customSetters' not found on object of type 'JSONModelClassProperty *'; did you mean 'customGetter'?
Error:(37, 29) property 'customSetters' not found on object of type 'JSONModelClassProperty *'; did you mean 'customGetter'?
Error:(37, 42) member reference base type 'SEL' is not a structure or union

**Comment by billinghamj** [comment]
Use Xcode 7.

**Comment by sudhiryadav** [comment]
Yes, that's true i tried with Xcode 7.2 an its working. But is there a limitation for ver 1.2.0 that it would not work with XCode 6.4. Please note that i cannot move to 7+ because that would require days :)

**Comment by billinghamj** [comment]
Probably comes down to the Obj-C generics syntax I suspect. Will look into it in more detail later and see whether I can make it compatible or not.

**Comment by hfossli** [comment]
Macros can be helpful to conditionally add generics tagging.
sø. 14. feb. 2016 kl. 13:24 skrev James Billingham <notifications@github.com

**Comment by sudhiryadav** [comment]
One final question : Is it official that xcode 6.4 is not supported by version 1.2.0?

**Comment by sudhiryadav** [comment]
@hfossli, If you have done something on this then can you share the sample please?

**Comment by hfossli** [comment]
@sudhiryadav https://gist.github.com/smileyborg/d513754bc1cf41678054

**Comment by billinghamj** [comment]
I have corrected this in 1c6046f793f8726f5fff7c9ff84ad4d74924b254. That being said, I would say that we do not guarantee support for old versions of Xcode, but make a best-effort attempt to do so.
